plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-sh"
importOrder:
  - "^node"
  - "^vue"
  - "^(vite|vite/)$"
  - "^vitepress"
  - "^vitest"
  - "^[^.]"
  - "^[./]"
importOrderSeparation: true
importOrderSortSpecifiers: true
